/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.portfolio.Portfolio;

public class App {
    private static final int sleepTime = 1000;

    public static void main(String[] args) {
        
        Portfolio p = new Portfolio();
        p.load();

        try {
            while(true){
                    System.out.println("\033[H\033[2J");
                    System.out.println("====================================================================================================================");
                    System.out.println("|Ticker                   |Shares   |Type  |Strike      |Maturity          |Asset    |Price       |Value           |");
                    System.out.println("====================================================================================================================");
                    p.getProducts().values().forEach(System.out::println);
                    System.out.println("====================================================================================================================");
                    System.out.println();
                    System.out.println();
                    System.out.println("=====================");
                    System.out.println("NAV: " + p.getNAV());
                    System.out.println("=====================");
                    System.out.println("Ctrl + C to exit");
                    Thread.sleep(sleepTime);
            }
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        
    }
}
